# Generated by Django 6.0.1 on 2026-03-05 15:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0010_employeeconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='employee_videos/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('fps_used', models.IntegerField(default=10)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_uploads', to='surveys.employee')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BAD_POSTURE', 'BAD_POSTURE'), ('HIGH_BLINK', 'HIGH_BLINK'), ('REPETITIVE_MOTION', 'REPETITIVE_MOTION')], max_length=30)),
                ('start_sec', models.FloatField()),
                ('end_sec', models.FloatField()),
                ('severity', models.IntegerField(default=3)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='vision.videoupload')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posture_score', models.FloatField(default=0)),
                ('posture_status', models.CharField(default='UNKNOWN', max_length=10)),
                ('bad_posture_pct', models.FloatField(default=0)),
                ('blink_rate_per_min', models.FloatField(blank=True, null=True)),
                ('perclos', models.FloatField(blank=True, null=True)),
                ('repetitive_motion_score', models.FloatField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='vision.videoupload')),
            ],
        ),
    ]
