# Generated by Django 4.2.11 on 2026-03-24 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_posturemetric'),
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysisresult',
            name='posture_status',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.CreateModel(
            name='RealtimeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.FloatField(default=0)),
                ('eye_closed_time', models.FloatField(default=0)),
                ('blink_count', models.IntegerField(default=0)),
                ('posture_time', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.employee')),
            ],
        ),
    ]
