# Generated by Django 4.2.11 on 2026-03-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_alter_videoanalysisresult_posture_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimemetrics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
