# Generated by Django 4.2.11 on 2026-03-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0003_alter_realtimemetrics_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimemetrics',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
