# Generated by Django 4.2.11 on 2026-05-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0004_alter_realtimemetrics_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimemetrics',
            name='blink_rate_per_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='realtimemetrics',
            name='ear_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='realtimemetrics',
            name='microsleep_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realtimemetrics',
            name='perclos',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='realtimemetrics',
            name='visual_fatigue_score',
            field=models.FloatField(default=0),
        ),
    ]
