# Generated by Django 6.0.1 on 2026-02-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_hash', models.CharField(max_length=256, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('seniority', models.CharField(blank=True, max_length=20)),
                ('work_mode', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_profile_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
