# Generated by Django 6.0.1 on 2026-02-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_question_options_alter_answer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.CharField(max_length=80),
        ),
    ]
