# Generated by Django 6.0.1 on 2026-02-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_question_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='surveyresponse',
            name='surveys_sur_employe_d1f6ed_idx',
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(fields=('employee', 'survey'), name='uniq_employee_survey'),
        ),
    ]
