# Generated by Django 6.0.1 on 2026-02-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_remove_surveyresponse_surveys_sur_employe_d1f6ed_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='surveyresponse',
            name='uniq_employee_survey',
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(fields=('employee', 'survey', 'submitted_at'), name='uniq_emp_survey_datetime'),
        ),
    ]
