# Generated by Django 6.0.1 on 2026-02-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_remove_surveyresponse_uniq_employee_survey_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='surveyresponse',
            name='uniq_emp_survey_datetime',
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(fields=('employee', 'survey'), name='uniq_employee_survey'),
        ),
    ]
