# Generated by Django 6.0.1 on 2026-02-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_remove_surveyresponse_uniq_emp_survey_datetime_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('response', 'question')},
        ),
    ]
