# Generated by Django 6.0.1 on 2026-03-02 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_alter_answer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history', models.JSONField(default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.employee')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('employee', 'survey', 'round_number')},
            },
        ),
    ]
