# Generated by Django 4.2.11 on 2026-03-23 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_employeeconversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostureMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_time', models.FloatField(default=0)),
                ('eye_closed_time', models.FloatField(default=0)),
                ('blink_count', models.IntegerField(default=0)),
                ('tete_penchee_time', models.FloatField(default=0)),
                ('cou_vers_avant_time', models.FloatField(default=0)),
                ('epaules_arrondies_time', models.FloatField(default=0)),
                ('dos_courbe_time', models.FloatField(default=0)),
                ('fatigue_visuelle_time', models.FloatField(default=0)),
                ('score', models.FloatField(default=100)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='posture_videos/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posture_metrics', to='surveys.employee')),
            ],
        ),
    ]
