# Generated by Django 4.2.11 on 2026-05-03 18:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_posturemetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_analyses/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('emotion', models.CharField(max_length=50)),
                ('emotion_confidence', models.FloatField(default=0.0)),
                ('audio_features', models.JSONField(blank=True, default=dict)),
                ('current_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('desired_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'voice_analysis',
                'ordering': ['-created_at'],
            },
        ),
    ]
