# Generated by Django 4.2.11 on 2026-05-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_voiceanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceanalysis',
            name='audio_features',
        ),
        migrations.RemoveField(
            model_name='voiceanalysis',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='voiceanalysis',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='voiceanalysis',
            name='match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='voiceanalysis',
            name='recommended_position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='voiceanalysis',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
