# Generated by Django 4.2.11 on 2026-05-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_voiceanalysis_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceanalysis',
            name='all_recommendations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='voiceanalysis',
            name='is_sent_to_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voiceanalysis',
            name='validated_positions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='voiceanalysis',
            name='current_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='voiceanalysis',
            name='desired_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='voiceanalysis',
            name='emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='voiceanalysis',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='voiceanalysis',
            table=None,
        ),
    ]
